### ISSUE TITLE
Organization/Shinies

### ISSUE THREAD

**Issue by meowingLexi** [itsjavi/livingdex#3]
Hello, 
First of all just let me say this is my opinion and as such it can be disregarded in full. Moving on I've noticed that you seem to be sorting according to the national dex value. While I can agree that it makes it easy to tell if someone is in the wrong place and it gives an easy way to sort the Pokemon. I can't help but feel as if it's not the most pleasing to look at. 

As a designer and as a live dex owner I feel it's more aesthetically pleasing by putting them in groups much like that Twitter video showed. Of course I could be biased as that's how I have mine except with shiny dex between the live dex and the form dex. 

I feel by separating the base forms from the additional forms would make it easier to read and sort as a human. I say this as I had to sort mine by hand lol... Actually thinking about it in terms of objects if each Pokemon has an ID say their Ndex number then an additional sub ID or object modifier for forms; take Vivillion for example, you could ID it as (666_01) as the Ndex number and the form ID. 

Just take the most accepted way of sorting them and number then accordingly. It should then be possible to make a sorting system where you can isolate and reorder groups of Pokemon. Say just the base forms or the regional variants. Anyway I'm not a programmer so I'm not sure how much of this is even possible and I assume it's fairly complex to do what I said in an UI friendly way. Either way I look forward to the future of this project as it would've helped me when I was sorting my Pokemon. I would also like to see the addition of the shiny Pokemon. But you know one step at a time.

**Comment by lloyd094** [comment]
In regards to shinies, I would personally have three options: Normal (the current version), Shiny (just shines) and both (Normal following with shiny). I think this would be incredibly helpful, and hopefully not much extra work in general?

**Comment by meowingLexi** [comment]
Yeah I could see that working.

--
Best Regards,


Alexandra Hunter
(971) 724-1043
Lexihuntermodeling.com
Lexihuntermodeling@gmail.com

**Comment by itsjavi** [comment]
Hey thank you all for the feedback, for some reason I missed the notifications regarding the open issues of this project.

>  in groups much like that Twitter video showed
@meowingLexi what video is that?

In the current version, everything is sorted according to the national dex number + the forms order in Pokemon HOME pokedex.

Definitely I'd like to support multiple living dex sorting styles, but I don't know which ones other people are using. What I thought was to keep national dex sorting with some filter options (that can be set as 'subsequent' / 'in separated boxes' / 'off'):

- Add female variants
- Add shinies
- Add regional variants
- Add other forms (e.g. hat pikachus, deoxys forms)

But first I need to rewrite the project to use ReactJS instead of Gatsby (which generates a static page like we have right now).

Here you can see a list of planned features: https://github.com/itsjavi/livingdex/projects/1

I hope I have time soon for what I am planning for this project. I agree that the current sorting system is not perfect and if they add new forms everything will have to be reorganised again manually. Hopefully that happens just once a year usually, when they release new games, but I've felt the pain when they released the World-Cap Pikachu and I had to shift one place all following Pokes :D

So yes, many improvements will come soon hopefully :) 

Thanks
